# Generated by Django 4.2.15 on 2024-12-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="type",
            new_name="account_type",
        ),
        migrations.RemoveField(
            model_name="job",
            name="applicants",
        ),
        migrations.AddField(
            model_name="account",
            name="saved_jobs",
            field=models.ManyToManyField(
                blank=True, related_name="saved_jobs", to="Models.job"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=100)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Models.job"
                    ),
                ),
            ],
        ),
    ]
