# Generated by Django 4.2.15 on 2024-12-12 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0002_rename_type_account_account_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="contact_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="sex",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, upload_to="company_logos")),
                ("address", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
