# Generated by Django 4.2.15 on 2024-12-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0003_account_address_account_contact_number_account_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Models.company"
            ),
        ),
    ]
