# Generated by Django 4.2.15 on 2024-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0004_alter_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slots",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(default="Open", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="job_thumbnails"),
        ),
    ]
