# Generated by Django 4.2.15 on 2024-12-12 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0005_job_slots_job_status_job_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
    ]
