# Generated by Django 4.2.15 on 2024-12-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0007_remove_company_location_job_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
