# Generated by Django 4.2.15 on 2024-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0009_userresume"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(default="Full Time", max_length=100),
        ),
    ]
