# Generated by Django 4.2.15 on 2024-12-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0010_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
