# Generated by Django 5.1.5 on 2025-01-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/profile_pictures'),
        ),
        migrations.AddField(
            model_name='account',
            name='social_media',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
