# Generated by Django 5.1.5 on 2025-01-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0012_account_profile_picture_account_social_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='otp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
