# Generated by Django 5.1.5 on 2025-02-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0015_job_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='education_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='resume_attachments'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='resume_attachments'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='skills_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='resume_attachments'),
        ),
    ]
